package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Medicament implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String title;
	private long group;

	public Medicament() {
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public long getGroup() {
		return this.group;
	}

	public void setGroup(long group) {
		this.group = group;
	}

	public Medicament(java.lang.String title, long group) {
		this.title = title;
		this.group = group;
	}

}