package com.myspace.encyclopediaofdrugs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MedicamentTypeDTO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MedicamentTypeDTO() {
    }




}