package com.myspace.encyclopediaofdrugs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MedicamentGroup implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String title;
	private java.lang.String description;

	public MedicamentGroup() {
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public MedicamentGroup(java.lang.String title, java.lang.String description) {
		this.title = title;
		this.description = description;
	}

}