package com.myspace.encyclopediaofdrugs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MedicamentInterract implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String description;
	private java.lang.Boolean canInterract;

	private com.myspace.encyclopediaofdrugs.Medicament medicament1;

	private com.myspace.encyclopediaofdrugs.Medicament medicament2;

	public MedicamentInterract() {
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Boolean getCanInterract() {
		return this.canInterract;
	}

	public void setCanInterract(java.lang.Boolean canInterract) {
		this.canInterract = canInterract;
	}

	public com.myspace.encyclopediaofdrugs.Medicament getMedicament1() {
		return this.medicament1;
	}

	public void setMedicament1(
			com.myspace.encyclopediaofdrugs.Medicament medicament1) {
		this.medicament1 = medicament1;
	}

	public com.myspace.encyclopediaofdrugs.Medicament getMedicament2() {
		return this.medicament2;
	}

	public void setMedicament2(
			com.myspace.encyclopediaofdrugs.Medicament medicament2) {
		this.medicament2 = medicament2;
	}

	public MedicamentInterract(java.lang.String description,
			java.lang.Boolean canInterract,
			com.myspace.encyclopediaofdrugs.Medicament medicament1,
			com.myspace.encyclopediaofdrugs.Medicament medicament2) {
		this.description = description;
		this.canInterract = canInterract;
		this.medicament1 = medicament1;
		this.medicament2 = medicament2;
	}

}