package com.myspace.encyclopediaofdrugs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MedicamentInterract implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String description;
	private java.lang.Boolean canInterract;

	public MedicamentInterract() {
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Boolean getCanInterract() {
		return this.canInterract;
	}

	public void setCanInterract(java.lang.Boolean canInterract) {
		this.canInterract = canInterract;
	}

	public MedicamentInterract(java.lang.String description,
			java.lang.Boolean canInterract) {
		this.description = description;
		this.canInterract = canInterract;
	}

}