package com.myspace.encyclopediaofdrugs;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Medicament implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.Column(unique = true)
	private java.lang.String title;
	private MedicamentGroup group;

	private com.myspace.encyclopediaofdrugs.MedicamentFormula formula;

	private com.myspace.encyclopediaofdrugs.MedicamentType type;

	private com.myspace.encyclopediaofdrugs.ActiveSubstance activeSubstances;

	public Medicament() {
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public com.myspace.encyclopediaofdrugs.MedicamentGroup getGroup() {
		return this.group;
	}

	public void setGroup(com.myspace.encyclopediaofdrugs.MedicamentGroup group) {
		this.group = group;
	}

	public com.myspace.encyclopediaofdrugs.MedicamentFormula getFormula() {
		return this.formula;
	}

	public void setFormula(
			com.myspace.encyclopediaofdrugs.MedicamentFormula formula) {
		this.formula = formula;
	}

	public com.myspace.encyclopediaofdrugs.MedicamentType getType() {
		return this.type;
	}

	public void setType(com.myspace.encyclopediaofdrugs.MedicamentType type) {
		this.type = type;
	}

	public com.myspace.encyclopediaofdrugs.ActiveSubstance getActiveSubstances() {
		return this.activeSubstances;
	}

	public void setActiveSubstances(
			com.myspace.encyclopediaofdrugs.ActiveSubstance activeSubstances) {
		this.activeSubstances = activeSubstances;
	}

	public Medicament(java.lang.String title,
			com.myspace.encyclopediaofdrugs.MedicamentGroup group,
			com.myspace.encyclopediaofdrugs.MedicamentFormula formula,
			com.myspace.encyclopediaofdrugs.MedicamentType type,
			com.myspace.encyclopediaofdrugs.ActiveSubstance activeSubstances) {
		this.title = title;
		this.group = group;
		this.formula = formula;
		this.type = type;
		this.activeSubstances = activeSubstances;
	}

}